In [2]:
# Numpy - Numerical Python 
# Faster than Python Lists
import numpy as np
npArr = np.array([1,2,3])

#Check the Type of the Object
print(type(npArr))

# Difference between List and numpy array
print ("The Numpy Array - ")
print(npArr)

# Numpy Version of "range" function
print("Using ARange function with numpy")
print(np.arange(0,5))
# 0 =  starting point , 11 = End Point , 2 = Step size
print(np.arange(0,20,5))
# I want 3 linearly spaced numbers between 0 to 10
print("Linearly spaced numbers between 0 to 10")
print(np.linspace(0,10,50))

# ADDITION WITH NUMPY ARRAYS
print ("Addition with Numpy Arrays")
print (npArr + 2)
print (npArr + npArr)

# MULTIPLICATION OF NUMPY ARRAYS
print ("Multiplication of Numpy Arrays - ")
print(npArr**2)

#SQUARE ROOT OF NUMPY ARRAY
print("Square Root of Numpy array")
print (np.sqrt(npArr))
# LOG OF THE NUMPY ARRAY
print("Log of Numpy Array")
print(np.log(npArr))
# EXPONENTIAL OF A NUMPY ARRAY
print("Exponential of Numpy Array")
print(np.exp(npArr))

# IMPORTANT - If you want to perform all of the above functions with a List , you need to use a for loop
# which is slow and hence numpy array are more  convenient



<class 'numpy.ndarray'>
The Numpy Array - 
[1 2 3]
Using ARange function with numpy
[0 1 2 3 4]
[ 0  5 10 15]
Linearly spaced numbers between 0 to 10
[  0.           0.20408163   0.40816327   0.6122449    0.81632653
   1.02040816   1.2244898    1.42857143   1.63265306   1.83673469
   2.04081633   2.24489796   2.44897959   2.65306122   2.85714286
   3.06122449   3.26530612   3.46938776   3.67346939   3.87755102
   4.08163265   4.28571429   4.48979592   4.69387755   4.89795918
   5.10204082   5.30612245   5.51020408   5.71428571   5.91836735
   6.12244898   6.32653061   6.53061224   6.73469388   6.93877551
   7.14285714   7.34693878   7.55102041   7.75510204   7.95918367
   8.16326531   8.36734694   8.57142857   8.7755102    8.97959184
   9.18367347   9.3877551    9.59183673   9.79591837  10.        ]
Addition with Numpy Arrays
[3 4 5]
[2 4 6]
Multiplication of Numpy Arrays - 
[1 4 9]
Square Root of Numpy array
[ 1.          1.41421356  1.73205081]
Log of Numpy Array
[ 0.          0.6931

In [3]:
# Calculate the dot product with numpy
A = np.array([1,2,3,4,5])
B = np.array([7,8,9,10,11])

# Using the following three ways we can calculate the dot product of numpy arrays
print("Dot product of the two arrays - ")
print(np.sum(A*B))
print((A*B).sum())
# Numpy has an in-built function for the dot product of array
print(np.dot(A,B))
# dot function is an instance method of numpy array. Hence we can use the given method also
print(A.dot(B))

Dot product of the two arrays - 
145
145
145
145


In [4]:
# Find out the cosine between two vectors
magnitude = np.sqrt( (A*A).sum())
print (magnitude)
print (np.linalg.norm(A))

cosangle = A.dot(B) / ( np.linalg.norm(A) * np.linalg.norm(B))
print (cosangle)

angle = np.arccos(cosangle)
print (angle)

7.4161984871
7.4161984871
0.959759918866
0.284650285298


In [5]:
# Matrix is a 2-dimensional Array
# First index of both the lists is a row and second is the column
M = np.array([[1,2], [3,4]])

# Printing the elements of the 2-D Numpy Array
print (M[0,0])

# Declare a matrix
M2 = np.matrix([ [1,2], [3,4]])
print (M2)
A1 = np.array(M2)
print (A1)
#Declare an Identity Matrix
print(np.eye(3))

1
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [6]:
# Create an vector of lenght = 10 and containing all zeros
print (np.zeros(10))

# Create an 2D matrix of zeros
print (np.zeros((10,10)))

# Create an 2D matrix of ones
print (np.ones((10,10)))

# Create an 2D matrix of random numbers
# This "random" function gives us uniformly distributed values between '0' and '1'
print (np.random.random((10,10)))

# Create an 2D matrix of random numbers using gaussian distribution
# These numbers have mean = 0 and variance = 1
G = np.random.randn(10,10)
print(G)
print ("The mean - ")
print(G.mean())
print ("The variance - ")
print(G.var())


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 0.84394088  0.649796    0.98338538  0.12631841  0.97723155  0.37552882
   0.11606952  0.62384

In [7]:
# Calculate a Matrix Inverse
#A2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
#A2 = np.array([[10,12],[13,14]])
A2 = np.array([[1,2],[3,4]])
AInv = np.linalg.inv(A2)
print(AInv)

# Get the Identity Matrix
IdentityMat = A2.dot(AInv) 
print(IdentityMat)

# get a determinant of a matrix
MatDet = np.linalg.det(A2)
print (MatDet)

# Get the diagonal elements of matrix
print(np.diag(A2))

# Get daigonal elements of a vector
print(np.diag([1,2]))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]
-2.0
[1 4]
[[1 0]
 [0 2]]


In [8]:
C = np.array([10,11])
D = np.array([12,13])

# The outer product of above two vectors is as follows:
MatOuter = np.outer(C,D)
print(np.outer(C,D))

# The inner product
print(np.inner(C,D))

# Matrix Trace - Sum of the diagonal elements of a matrix
print(np.diag(MatOuter).sum())
print(np.trace(MatOuter))

[[120 130]
 [132 143]]
263
263
263


In [9]:
# EigenValues and EigenVectors
# the given array has 100 samples and 3 features
X = np.random.randn(100,3)

# Covariance of X
cov = np.cov(X.T)
print(cov.shape)
print(cov)

# Find Eigenvalues and EigenVectors
print(np.linalg.eigh(cov))
print(np.linalg.eig(cov))

(3, 3)
[[ 1.14733487 -0.04973489 -0.02068318]
 [-0.04973489  0.9914336   0.03474246]
 [-0.02068318  0.03474246  1.07535974]]
(array([ 0.96942857,  1.07334344,  1.1713562 ]), array([[ 0.23144226,  0.36705188, -0.90094805],
       [ 0.93688189,  0.16539193,  0.30805493],
       [-0.26208168,  0.91537884,  0.30560558]]))
(array([ 1.1713562 ,  0.96942857,  1.07334344]), array([[-0.90094805,  0.23144226,  0.36705188],
       [ 0.30805493,  0.93688189,  0.16539193],
       [ 0.30560558, -0.26208168,  0.91537884]]))


In [10]:
# Solving a Linear System
# Ax = b , where A = Matrix , x= column vector and b = vector of numbers
A3 = np.array([[1,2],[3,4]])
B3 = np.array([1,2])

# Solution is as follows
print(np.linalg.solve(A3 , B3))

[ 0.   0.5]


In [11]:
# The admission fee at a samll fair is $1.50 for children and $4.00 for adult. One a day , 2200 people
#visisted the fair and $5050 amount was collected. How many childrena and how many adults?
# X1 = number of children and X2 = number of adults
# X1 + X2 = 2200
# 1.5X1 + 4X2 = 5050
# Lets solve using numpy 
AD = np.array([[1,1], [1.5,4]])
CD = np.array([2200,5050])

print(np.linalg.solve(AD, CD))
# 1500 children
# 700 Adults

[ 1500.   700.]


In [12]:
# Reshape the Array
X = np.arange(25)
print (X)
print (X.reshape(5,5))
#Max number in array
print ("The max in the array and the index")
print (X.max())
print (X.argmax())

#Max number in array
print ("The min in the array and the index")
print (X.min())
print (X.argmin())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
The max in the array and the index
24
24
The min in the array and the index
0
0
